### ISSUE TITLE
Config for bch node address

### ISSUE THREAD

**Issue by alexqrid** [Bitcoin-com/slp-indexer#5]
I have a BCH node running on my server and want to run this slp-indexer on another server. Where should I specify my BCH node address and port?

**Comment by AndreasLarssons** [comment]
Hey!
put your nodes in the application-prod.properties using this config. I updated the readme to include this info

bitcoinj.peers.bch=127.0.0.1:8333,127.0.0.2:8333

**Comment by alexqrid** [comment]
>  I updated the readme to include this info

Thank you!
I have already changed some parameters, such as `spring.data.mongodb.uri` and `spring.data.mongodb.database` in this config [application-prod.properties](../blob/master/slp-indexer-service/slp-indexer-service-app/src/main/resources/application-prod.properties)(because my mongod is not listening on the default 27017 port) and run the indexer with this command:
```
java -jar -Dspring.profiles.active=prod slp-indexer-service-app-0.0.1-SNAPSHOT-exec.jar
```
But the application was trying to connect on default port and as a result was waiting for connection 30000 ms. So does this config really matter? Because my changes didn't affect anything.
My config looks like this:
```
svp.header.store=/var/blockchain/indexer/spvheaderstore


bitcoinj.max.connection=1
bitcoinj.awaiting.peer=1
#dns.discovery=DNS_TO_YOUR_NODES
spring.data.mongodb.uri=mongodb://username:password@localhost:15842/bicash
spring.data.mongodb.database=bicash


spring.application.name=slp-indexer-service
logging.level.org.bitcoinj=INFO

bitcoinj.download.chain=true
bitcoinj.version=0.15
bitcoinj.type=BitcoinCashJ
blockchain.coin=BCH


is.indexer=true

```
<details><summary>Logs</summary>

```
2020-01-22 12:09:34.329  INFO 8868 --- [main] com.bitcoin.indexer.Main                 : The following profiles are active: prod
2020-01-22 12:09:35.456  INFO 8868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2020-01-22 12:09:35.458  INFO 8868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-01-22 12:09:35.494  INFO 8868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 30ms. Found 0 repository interfaces.
2020-01-22 12:09:35.500  INFO 8868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2020-01-22 12:09:35.500  INFO 8868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-01-22 12:09:35.508  INFO 8868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8ms. Found 0 repository interfaces.
2020-01-22 12:09:35.522  INFO 8868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2020-01-22 12:09:35.524  INFO 8868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-01-22 12:09:35.539  INFO 8868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 6ms. Found 0 repository interfaces.
2020-01-22 12:09:35.942  INFO 8868 --- [main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=3bda0e60-d6d6-33b6-af12-a00859133cc5
2020-01-22 12:09:36.018  INFO 8868 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$e0a0169f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-01-22 12:09:36.555  INFO 8868 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 7331 (http)
2020-01-22 12:09:36.673  INFO 8868 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-01-22 12:09:36.674  INFO 8868 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.14]
2020-01-22 12:09:36.695  INFO 8868 --- [main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
2020-01-22 12:09:36.822  INFO 8868 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/api]    : Initializing Spring embedded WebApplicationContext
2020-01-22 12:09:36.823  INFO 8868 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2476 ms
2020-01-22 12:09:37.377  INFO 8868 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-01-22 12:09:37.569  INFO 8868 --- [cluster-ClusterId{value='5e283b81504afa22a47ede2b', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:158) ~[mongodb-driver-core-3.8.2.jar!/:na]
        at com.mongodb.connection.netty.NettyStream$2.operationComplete(NettyStream.java:145) ~[mongodb-driver-core-3.8.2.jar!/:na]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[netty-common-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[netty-common-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-common-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) ~[netty-common-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-common-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.31.Final.jar!/:4.1.31.Final]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[na:na]
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.31.Final.jar!/:4.1.31.Final]
        ... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused
        ... 11 common frames omitted

2020-01-22 12:09:37.680  INFO 8868 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-01-22 12:09:37.694  INFO 8868 --- [cluster-ClusterId{value='5e283b81504afa22a47ede2c', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar!/:na]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar!/:na]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
        at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar!/:na]
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar!/:na]
        ... 3 common frames omitted

2020-01-22 12:09:38.212  INFO 8868 --- [main] org.mongodb.driver.cluster               : Cluster description not yet available. Waiting for 30000 ms before timing out

```
</details>

**Comment by AndreasLarssons** [comment]
I just tested this with my a local copy and it runs just fine with this connectionstring with a mongodb running on port 1333 instead of 27017.

```
svp.header.store=/var/blockchain/indexer/spvheaderstore


#bitcoinj.max.connection=MAX_AVAILABLE_NODES
#bitcoinj.awaiting.peer=PEERS_NEEDED_FOR_STARTUP
#dns.discovery=DNS_TO_YOUR_NODES
spring.data.mongodb.uri=mongodb://username:password@localhost:1333/open-source
spring.data.mongodb.database=open-source
#bitcoinj.peers.bch=127.0.0.1:8333,127.0.0.2:8333


spring.application.name=slp-indexer-service
logging.level.org.bitcoinj=INFO

bitcoinj.download.chain=true
bitcoinj.version=0.15
bitcoinj.type=BitcoinCashJ
blockchain.coin=BCH


is.indexer=true
```

`java -jar -Dspring.profiles.active=prod slp-indexer-service-app-0.0.1-SNAPSHOT-exec.jar`

```
2020-01-27 15:18:42.809  INFO 47067 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:1333], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-01-27 15:18:42.815  INFO 47067 --- [localhost:1333] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:202}] to localhost:1333
```

With the config

```
spring.data.mongodb.uri=mongodb://username:password@localhost:270171/slpblockchain
```
I get this error below as expected
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reactiveStreamsMongoClient' defined in class path resource [org/springframework/boot/autoconfigure/mongo/MongoReactiveAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mongodb.reactivestreams.client.MongoClient]: Factory method 'reactiveStreamsMongoClient' threw exception; nested exception is java.lang.IllegalArgumentException: The connection string contains an invalid host 'localhost:270171'. The port '270171' is not a valid, it must be an integer between 0 and 65535
```

So I can't seem to reproduce your issue, the configuration seems to be applied correctly. Did you build the project with maven clean install after changing the config? Otherwise this config will not be included in the built jar.

If you want you can place a applications-prod.properties file next to the jar in the folder and then this config should also be picked up on launch.
